### PR TITLE
Add className property to SwipeableListProps for grid alignment needs

### PR DESCRIPTION
**Pull request by elmesaoudee**

### CODE REVIEW

**Comment by elmesaoudee** [comment]
I added className property to SwipeableListProps in order to make it adaptable to grid systems. I use the library with tailwind and I found out that SwipeableList needs to have className property in order to behave like a "col". 

The className property was already taken into consideration in the code, it just was not declared in SwipeableListProps which resulted in an error since I'm using typescript. 

Kindly accept the PR. 

Best regards.

**Comment by marekrozmus** [comment]
@all-contributors please add @elmesaoudee for code

@elmesaoudee Thank you!

**Comment by marekrozmus** [comment]
@elmesaoudee New version 1.7.1 released :)

**Comment by elmesaoudee** [comment]
Awesome! Thanks guys :)

**Pull request merged**
